- name: Start OpenShift VM
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Start VM
      kubernetes.core.k8s:
        state: patched
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: test
            namespace: virtual-machines
          spec:
            running: true
